name: test_appifylab
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  formz: ^0.8.0
  auto_route: ^9.2.2
  get_it: ^8.0.3
  dio: ^5.7.0
  retrofit: ^4.4.2
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  flutter_reaction_button: ^3.0.0+3
  jiffy: ^6.3.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
